### PR TITLE
boardswarm: Add example systemd service & udev rules

### PR DESCRIPTION
**Pull request by obbardc**
Add an example systemd service file to the share directory.

### CODE REVIEW

**Comment by sjoerdsimons** [comment]
can you add a reference to the file in the documentation as well

**Comment by mwelchuk** [comment]
> For what it's worth, this systemd unit and udev rule works for me.

Spoke to soon. For reasons I needed to reboot my machine. After reboot, even with the udev rules in the other patch added, the TTYs aren't set to the correct group. I think the issue is that the udev rules are running before boardswarm is started. As a result, the (dyanmic) user doesn't actually exist and thus the required configuration isn't applied.

I think this really needs to have a system user and group created as part of install and these set in the systemd unit.

**Comment by mwelchuk** [comment]
Could you also add the udev rules that would be required for DFU on TI devices?:
```
# Allow boardswarm to access TI devices when in DFU mode
ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="0451", ATTRS{idProduct}=="6162", GROUP="boardswarm"
ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="0451", ATTRS{idProduct}=="6165", GROUP="boardswarm"
```

**Comment by obbardc** [comment]
> Could you also add the udev rules that would be required for DFU on TI devices?:
> 
> ```
> # Allow boardswarm to access TI devices when in DFU mode
> ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="0451", ATTRS{idProduct}=="6162", GROUP="boardswarm"
> ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="0451", ATTRS{idProduct}=="6165", GROUP="boardswarm"
> ```

Done. I will squash commits on a future next update.

**Pull request merged**
